<footer>
  <div class="accueil">
    <p>Brasme Gaëtan / Dauby Kyllian</p>
  </div>
  <section id="social-media">
  <h2>Réseaux Sociaux</h2>
  <p>Restez connecté avec nous via nos réseaux sociaux :</p>
  <a href="lien-vers-votre-page-facebook" target="_blank">
    <img src="../img/facebook.png" alt="Facebook">
  </a>
  <a href="lien-vers-votre-page-X" target="_blank">
    <img src="../img/X.png" alt="X">
  </a>
</section>
</footer>
</body>
</html>