<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title>Bibliothèque</title>
    <link rel="stylesheet" href="css/modele.css" />
  </head>
  <header>
  <nav class="nav-bar">
    <a href="./index.php?action=defaut"><img class="logo" src="img/logo.png" alt="" /></a>
    <div class="accueil">
      <p class="accueil-p">
        <a href="./index.php?action=defaut"> Accueil </a>
      </p>
    </div>
    <div class="connexion">
      <p class="contact-p"><a href="./index.php?action=connexion">Connexion</a></p>
    </div>
    <div class="contact">
      <p class="contact-p"><a href="./index.php?action=contact">Contact</a></p>
    </div>
    <div>
      <a class="loupe-container" href="./index.php?action=chercher"><img class="loupe" src="img/loupe.png" alt="" /></a>
      <a href="./index.php?action=connexion&logout">Déconnecter</a>
    </div>
  </nav>
  </header>
  