<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title>Bibliothèque</title>
    <link rel="stylesheet" href="css/modele.css" />
  </head>
  <header>
  <nav class="nav-bar">
    <div class="Acceuil">
      <p class="Acceuil-p">
        <a href="./index.php?action=defaut"> Acceuil </a>
      </p>
    </div>
    <div class="connexion">
      <p class="connexion-p"><a href="./index.php?action=connexion">Connexion</a></p>
    </div>
    <div class="cookies">
      <p class="cookies-p"><a href="./index.php?action=cookies">Cookies</a></p>
    </div>
    <div class="contact">
      <p class="contact-p"><a href="./index.php?action=contact">Contact</a></p>
    </div>
    <div class="livres">
      <p class="livres-p">
        <a href="./index.php?action=livres">Livres</a>
      </p>

    </div>
  </nav>
  </header>
  