<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <title>Bibliothèque</title>
    <link rel="stylesheet" href="css/modele.css" />
  </head>
  <header>
<header>
      <nav class="navbar">
        <div class="nav-item">
          <a href="./index.php?action=defaut">Accueil</a>
        </div>
        <div class="nav-item">
          <a href="./index.php?action=cookies">Confidentialite</a>
        </div>
        <div class="nav-item">
          <a href="./index.php?action=contact">Contact</a>
        </div>
        <div class="nav-item">
          <a href="./index.php?action=livres">Livres</a>
        </div>
        <div class="nav-item">
          <a href="./index.php?action=connexion">Connexion</a>
        </div>
        <div class="nav-item">
          <a href="./index.php?action=connexion&logout">Déconnexion</a>
        </div>
      </nav>
    </header>
  </header>
  